import { CalendarIcon } from "./Calendar";
import { ClockIcon } from "./Clock";
import { QrIcon } from "./Qr";
import { GuestIcon } from "./Guest";
import { TrashIcon } from "./Trash";
import { LogoutIcon } from "./Exit";
import { HistoryIcon } from "./History";
import { EmailIcon } from "./Mail";
import { BellIcon } from "./Notification";
import { ProfileIcon } from "./Profile";
import { EyeIcon } from "./Eye";
import { MonitorIcon } from "./Topic";
import { SettingsIcon } from "./Settings";

export { CalendarIcon };
export { ClockIcon };
export { QrIcon };
export { GuestIcon };
export { TrashIcon };
export { LogoutIcon };
export { HistoryIcon };
export { EmailIcon };
export { BellIcon };
export { ProfileIcon };
export { EyeIcon };
export { MonitorIcon };
export { SettingsIcon };
