import { CalendarIcon } from "./Calendar";
import { ClockIcon } from "./Clock";
import { QrIcon } from "./Qr";
import { GuestIcon } from "./Guest";
import { TrashIcon } from "./Trash";
import { LogoutIcon } from "./Exit";
import { HistoryIcon } from "./History";
import { EmailIcon } from "./Mail";
import { BellIcon } from "./Notification";
import { ProfileIcon } from "./Profile";
import { EyeIcon } from "./Eye";
import { MonitorsIcon } from "./Topic";
import { SettingsIcon } from "./Settings";
import { SearchIcon } from "./Search";
import { MapIcon } from "./Map";
import { MonitorIcon } from "./Monitor";
import { ClockMapIcon } from "./ClockMap";
import { FilterIcon } from "./Filter";

export { CalendarIcon };
export { ClockIcon };
export { QrIcon };
export { GuestIcon };
export { TrashIcon };
export { LogoutIcon };
export { HistoryIcon };
export { EmailIcon };
export { BellIcon };
export { ProfileIcon };
export { EyeIcon };
export { MonitorsIcon };
export { SettingsIcon };
export { SearchIcon };
export { MapIcon };
export { MonitorIcon };
export { ClockMapIcon };
export { FilterIcon };
